#zf210107.1146, zf221201.0952
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb/server:10.3

    volumes:
      - $PWD/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always
    ports:
      - "3306:3306"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
        MYSQL_USER: root
        PMA_HOST: db

      # - PMA_ARBITRARY=1
